version: '3.8'

services:
  app:
    build: .
    container_name: idra_ai_chatbot
    ports:
      - "3000:3000"
    env_file:
      - .env.test
    depends_on:
      - mongo
      - chromadb
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: orion_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: rag_chroma
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    restart: unless-stopped

volumes:
  mongo_data:
  chromadb_data:

networks:
  default:
    name: rag_network
